# Generated by Django 2.1 on 2019-02-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='posture',
            field=models.ImageField(default=1, upload_to='event_logos'),
            preserve_default=False,
        ),
    ]
