# Generated by Django 2.1 on 2019-02-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_boking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
