# Generated by Django 2.1 on 2019-02-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booking_number_of_boking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_boking',
        ),
    ]
