# Generated by Django 2.1 on 2019-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190226_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(choices=[('Choose City', 'Choose City'), ('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Dammam', 'Dammam'), ('Makkah', 'Makkah')], default='Choose City', max_length=12),
        ),
    ]
